### ISSUE TITLE
Integration with Relay

### ISSUE THREAD

**Issue by wealth** [rmosolgo/graphql-streaming#1]
Is it possible to integrate with https://github.com/edvinerikson/relay-subscriptions?
I've run into problem described in issue https://github.com/edvinerikson/relay-subscriptions/issues/22
According to https://github.com/taion/graphql-relay-subscription/blob/master/src/subscriptionWithClientId.js subscription probably should declare an input type and payload.

**Comment by dorthwein** [comment]
Same question ;(

**Comment by rmosolgo** [comment]
Sorry, it might be possible but I haven't done it! This library was mostly an experiment. I'll release a Relay client for graphql-ruby subscriptions before too long though, the main issue is rmosolgo/graphql-ruby#613
