### ISSUE TITLE
ActionCableSubscriber usage

### ISSUE THREAD

**Issue by valerybugakov** [rmosolgo/graphql-streaming#2]
Hey, thanks for this library!

I'm trying to setup a subscription and got confused by `ActionCableSubscriber` behavior.
I have a trigger for a specific subscription named `test`. 
```rb
class Notification
  after_touch :trigger_subscription

  def trigger_subscription
    GraphQL::Streaming::ActionCableSubscriber.trigger(:test, {"id":"588f2142c6e47b8f9cfc811c","clientSubscriptionId":"0"})
  end
end
```

When it gets triggered I see logs:
```
[ActionCable] Broadcasting to graphql_subscription_test: {:id=>"588f2142c6e47b8f9cfc811c", :clientSubscriptionId=>"0"}
``` 

It always broadcast to the same channel. Also it doesn't reevaluate the query sent from the client, it just send data listed in logs. 

Also I've tried to read through the source code and found some hardcoded prefix for the subscriber which is used to broadcast patches:
```rb
class ActionCableSubscriber
      CHANNEL_PREFIX = "graphql_subscription_"
      ....
```
Shouldn't it find any subscribers who requested a matching query and update them with reevaluated query result or my setup has some errors here?

**Comment by rmosolgo** [comment]
Yes, any subscribers who requested a matching query should [reevaluate in response](https://github.com/rmosolgo/graphql-streaming/blob/master/lib/graphql/streaming/action_cable_subscriber.rb#L58-L61) to that message!

What's an example query for subscribing to that event?

**Comment by denniszudin** [comment]
@rmosolgo thanks! `binding.pry` in this code block helped me fix subscription, everything works now!

**Comment by valerybugakov** [comment]
@rmosolgo thanks! `binding.pry` there helped me fix subscription, everything works now!

**Comment by rmosolgo** [comment]
:metal: have fun! I hope you noted the to-dos in the Readme of this gem, it's not exactly production-ready 😬
